# Generated by Django 5.2.17 on 2026-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessmentitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
