# Generated by Django 5.2.17 on 2026-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentitem_remarks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table='nis_assessment',
        ),
        migrations.AlterModelTable(
            name='assessmentitem',
            table='nis_assessment_item',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='nis_invoice',
        ),
    ]
