# Generated by Django 5.2.17 on 2026-09-18 12:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0002_seed_survey_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insured',
                'verbose_name_plural': 'Insured Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurer',
                'verbose_name_plural': 'Insurers',
                'ordering': ['company_name', 'branch_name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, unique=True)),
                ('policy_type', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excess', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('commodity', models.CharField(max_length=255)),
                ('subject_matter', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='claims.insurer')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('report_number', models.CharField(blank=True, max_length=50)),
                ('instruction_date', models.DateField()),
                ('instruction_source', models.CharField(max_length=255)),
                ('date_of_loss', models.DateField()),
                ('nature_of_loss', models.CharField(max_length=255)),
                ('loss_location', models.TextField()),
                ('claimed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(default='NEW', max_length=50)),
                ('claim_description', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('internal_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_created', to=settings.AUTH_USER_MODEL)),
                ('survey_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='surveys.surveytype')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.insured')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.insurer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.policy')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_given', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='claims.claim')),
                ('surveyor', models.ForeignKey(limit_choices_to={'role': 'SURVEYOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='survey_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Assignment',
                'verbose_name_plural': 'Survey Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['survey_type'], name='claims_clai_survey__ca08ab_idx'),
        ),
    ]
