# Generated by Django 5.2.17 on 2026-09-18 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('INSPECTION_PENDING', 'Inspection Pending'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('ILA_PREPARED', 'ILA Prepared'), ('LOR_ISSUED', 'LOR Issued'), ('DOCUMENT_COLLECTION', 'Document Collection'), ('ASSESSMENT_IN_PROGRESS', 'Assessment In Progress'), ('ISR_PREPARED', 'ISR Prepared'), ('FSR_PREPARED', 'FSR Prepared'), ('REPORT_SUBMITTED', 'Report Submitted'), ('CLOSED', 'Closed'), ('QUERY_RAISED', 'Query Raised'), ('REVISION_REQUIRED', 'Revision Required'), ('RESUBMITTED', 'Resubmitted'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=50),
        ),
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('INSPECTION_PENDING', 'Inspection Pending'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('ILA_PREPARED', 'ILA Prepared'), ('LOR_ISSUED', 'LOR Issued'), ('DOCUMENT_COLLECTION', 'Document Collection'), ('ASSESSMENT_IN_PROGRESS', 'Assessment In Progress'), ('ISR_PREPARED', 'ISR Prepared'), ('FSR_PREPARED', 'FSR Prepared'), ('REPORT_SUBMITTED', 'Report Submitted'), ('CLOSED', 'Closed'), ('QUERY_RAISED', 'Query Raised'), ('REVISION_REQUIRED', 'Revision Required'), ('RESUBMITTED', 'Resubmitted'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('new_status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('INSPECTION_PENDING', 'Inspection Pending'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('ILA_PREPARED', 'ILA Prepared'), ('LOR_ISSUED', 'LOR Issued'), ('DOCUMENT_COLLECTION', 'Document Collection'), ('ASSESSMENT_IN_PROGRESS', 'Assessment In Progress'), ('ISR_PREPARED', 'ISR Prepared'), ('FSR_PREPARED', 'FSR Prepared'), ('REPORT_SUBMITTED', 'Report Submitted'), ('CLOSED', 'Closed'), ('QUERY_RAISED', 'Query Raised'), ('REVISION_REQUIRED', 'Revision Required'), ('RESUBMITTED', 'Resubmitted'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_status_changes', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Claim Status History',
                'verbose_name_plural': 'Claim Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
