# Generated by Django 5.2.17 on 2026-09-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_status_claimstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REASSIGNED', 'Reassigned')], default='ASSIGNED', max_length=30),
        ),
    ]
