# Generated by Django 5.2.17 on 2026-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_surveyassignment_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='claim',
            new_name='nis_claim_status_fed1e4_idx',
            old_name='claims_clai_status_b4f911_idx',
        ),
        migrations.RenameIndex(
            model_name='claim',
            new_name='nis_claim_survey__8e3682_idx',
            old_name='claims_clai_survey__ca08ab_idx',
        ),
        migrations.AlterModelTable(
            name='claim',
            table='nis_claim',
        ),
        migrations.AlterModelTable(
            name='claimstatushistory',
            table='nis_claim_status_history',
        ),
        migrations.AlterModelTable(
            name='insured',
            table='nis_insured',
        ),
        migrations.AlterModelTable(
            name='insurer',
            table='nis_insurer',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='nis_policy',
        ),
        migrations.AlterModelTable(
            name='surveyassignment',
            table='nis_survey_assignment',
        ),
    ]
