# Generated by Django 5.2.17 on 2026-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_rename_claims_clai_status_b4f911_idx_nis_claim_status_fed1e4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='gstin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
