# Generated by Django 5.2.17 on 2026-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='surveyorprofile',
            table='nis_surveyor_profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='nis_user',
        ),
    ]
