# Generated by Django 5.2.17 on 2026-09-19 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_surveyassignment_status'),
        ('reports', '0002_fsr_ila_isr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='claims.claim'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['claim'], name='reports_aud_claim_i_71d183_idx'),
        ),
    ]
