# Generated by Django 5.2.17 on 2026-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auditlog_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsr',
            name='adequacy_of_sum_insured',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fsr',
            name='policy_coverage',
            field=models.TextField(blank=True),
        ),
    ]
