# Generated by Django 5.2.17 on 2026-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_fsr_adequacy_of_sum_insured_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='nis_audit_l_claim_i_3e4953_idx',
            old_name='reports_aud_claim_i_71d183_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='nis_audit_l_model_n_ced1c9_idx',
            old_name='reports_aud_model_n_dc47ea_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='nis_audit_l_action_1f3338_idx',
            old_name='reports_aud_action_c56ae5_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='nis_audit_l_timesta_22f804_idx',
            old_name='reports_aud_timesta_09f1cf_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='nis_audit_log',
        ),
        migrations.AlterModelTable(
            name='fsr',
            table='nis_fsr',
        ),
        migrations.AlterModelTable(
            name='ila',
            table='nis_ila',
        ),
        migrations.AlterModelTable(
            name='isr',
            table='nis_isr',
        ),
    ]
