# Generated by Django 5.2.17 on 2026-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_document_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claimdocument',
            table='nis_claim_document',
        ),
        migrations.AlterModelTable(
            name='documenttype',
            table='nis_document_type',
        ),
        migrations.AlterModelTable(
            name='requirement',
            table='nis_requirement',
        ),
    ]
