# Generated by Django 5.2.17 on 2026-09-18 12:39

import django.core.validators
import django.db.models.deletion
import surveys.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_status_claimstatushistory'),
        ('surveys', '0002_seed_survey_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('person_contacted', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('reason_for_delay', models.TextField(blank=True)),
                ('site_representative', models.CharField(blank=True, max_length=150)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='claims.claim')),
                ('surveyor', models.ForeignKey(limit_choices_to={'role': 'SURVEYOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_observations', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_list', to='surveys.inspection')),
            ],
            options={
                'verbose_name': 'Inspection Observation',
                'verbose_name_plural': 'Inspection Observations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only JPG, JPEG, and PNG image files are allowed.'), surveys.validators.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('SITE', 'Site'), ('DAMAGE', 'Damage'), ('MACHINERY', 'Machinery'), ('STOCK', 'Stock'), ('DOCUMENT', 'Document'), ('SALVAGE', 'Salvage'), ('OTHER', 'Other')], default='SITE', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='surveys.inspection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Photo',
                'verbose_name_plural': 'Inspection Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
