# Generated by Django 5.2.17 on 2026-09-19 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_status_claimstatushistory'),
        ('surveys', '0003_inspection_inspectionobservation_inspectionphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringClaimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('machine_location', models.CharField(blank=True, max_length=255)),
                ('breakdown_description', models.TextField()),
                ('damage_description', models.TextField()),
                ('cause_of_breakdown', models.TextField(blank=True)),
                ('repair_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('labour_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('testing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salvage', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_details', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Engineering Claim Details',
                'verbose_name_plural': 'Engineering Claim Details',
            },
        ),
        migrations.CreateModel(
            name='FireClaimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_details', models.TextField()),
                ('occupancy', models.CharField(max_length=255)),
                ('building_description', models.TextField()),
                ('fire_protection_details', models.TextField(blank=True)),
                ('fire_brigade_informed', models.BooleanField(default=False)),
                ('fire_brigade_details', models.TextField(blank=True)),
                ('police_informed', models.BooleanField(default=False)),
                ('police_details', models.TextField(blank=True)),
                ('fire_cause', models.TextField(blank=True)),
                ('cause_established', models.BooleanField(default=False)),
                ('point_of_origin', models.CharField(blank=True, max_length=255)),
                ('storage_details', models.TextField(blank=True)),
                ('machinery_details', models.TextField(blank=True)),
                ('stock_details', models.TextField(blank=True)),
                ('salvage_observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fire_details', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Fire Claim Details',
                'verbose_name_plural': 'Fire Claim Details',
            },
        ),
        migrations.CreateModel(
            name='MarineClaimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=255)),
                ('voyage_number', models.CharField(blank=True, max_length=100)),
                ('port_of_loading', models.CharField(max_length=150)),
                ('port_of_discharge', models.CharField(max_length=150)),
                ('place_of_survey', models.CharField(max_length=255)),
                ('cargo_description', models.TextField()),
                ('consignor', models.CharField(blank=True, max_length=255)),
                ('consignee', models.CharField(blank=True, max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('bill_of_lading_number', models.CharField(blank=True, max_length=100)),
                ('container_number', models.CharField(blank=True, max_length=100)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_description', models.TextField()),
                ('transit_details', models.TextField(blank=True)),
                ('packing_condition', models.TextField(blank=True)),
                ('salvage_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marine_details', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Marine Claim Details',
                'verbose_name_plural': 'Marine Claim Details',
            },
        ),
        migrations.CreateModel(
            name='PropertyClaimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=150)),
                ('occupancy', models.CharField(max_length=255)),
                ('construction_type', models.CharField(blank=True, max_length=150)),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('building_description', models.TextField(blank=True)),
                ('contents_description', models.TextField(blank=True)),
                ('stock_description', models.TextField(blank=True)),
                ('damage_description', models.TextField()),
                ('repair_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salvage', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Property Claim Details',
                'verbose_name_plural': 'Property Claim Details',
            },
        ),
    ]
