# Generated by Django 5.2.17 on 2026-09-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_engineeringclaimdetails_fireclaimdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='cause_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='extent_of_damage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='salvage_observations',
            field=models.TextField(blank=True),
        ),
    ]
