# Generated by Django 5.2.17 on 2026-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_inspection_cause_observations_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='engineeringclaimdetails',
            table='nis_engineering_claim_details',
        ),
        migrations.AlterModelTable(
            name='fireclaimdetails',
            table='nis_fire_claim_details',
        ),
        migrations.AlterModelTable(
            name='inspection',
            table='nis_inspection',
        ),
        migrations.AlterModelTable(
            name='inspectionobservation',
            table='nis_inspection_observation',
        ),
        migrations.AlterModelTable(
            name='inspectionphoto',
            table='nis_inspection_photo',
        ),
        migrations.AlterModelTable(
            name='marineclaimdetails',
            table='nis_marine_claim_details',
        ),
        migrations.AlterModelTable(
            name='propertyclaimdetails',
            table='nis_property_claim_details',
        ),
        migrations.AlterModelTable(
            name='surveytype',
            table='nis_survey_type',
        ),
    ]
